name: CompatHelper

on:
  schedule:
    - cron: '00 * * * *'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.6]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/bcbi/CompatHelper.jl.git"))'
      - name: CompatHelper.main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_DEBUG: CompatHelper
        run: julia -e 'using CompatHelper; CompatHelper.main()'
