name: Julia CI

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      feature:
        type: choice
        description: What to run
        options: [DocDeploy, LintAndTest, TagBot]

jobs:
  julia-ci:
    uses: julia-testitems/testitem-workflow/.github/workflows/juliaci.yml@v2
    with:
      include-windows-x86: false
      include-linux-x86: true

      allow-failure: "*~x86,*:macos-26-intel"

      env: '{"JULIA_PKG_PRECOMPILE_AUTO":"0","JULIA_NUM_PRECOMPILE_TASKS":"1"}'
      max-workers: "1"
      threads: "1"
      gc-between-testitems: "true"

      activation-timeout: "120"
      run-stall: "300"
      output-mode: "all"
      schedule: "contiguous"

    permissions: write-all
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}